version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: dog-adoption-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: adoptions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./src/main/resources/static/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
